// Seed data pre-filled on first run
import { Plan } from "../types";

export const SEED_PLAN: Plan = {
  id: "seed-plan-001",
  name: "Můj finanční plán",
  createdAt: "2026-04-24T00:00:00.000Z",
  updatedAt: "2026-04-24T00:00:00.000Z",
  baseline: {
    startDate: "2026-09",
    cashAccount: 1010000,
    investmentsBalance: 0,
    investmentsYieldAnnual: 0.05,
    safetyBufferMonths: 3,
    horizonYears: 30,
  },
  events: [
    {
      id: "evt-001",
      name: "Plat (net)",
      category: "income",
      amount: 50000,
      frequency: "monthly",
      startMonth: 0,
      endMonth: null,
      annualGrowthPct: 0,
    },
    {
      id: "evt-002",
      name: "Plat partnera (net)",
      category: "income",
      amount: 50000,
      frequency: "monthly",
      startMonth: 0,
      endMonth: null,
      annualGrowthPct: 0,
    },
    {
      id: "evt-003",
      name: "Energie + SVJ",
      category: "expense",
      amount: 8000,
      frequency: "monthly",
      startMonth: 0,
      endMonth: null,
      annualGrowthPct: 0.04,
    },
    {
      id: "evt-004",
      name: "Jídlo",
      category: "expense",
      amount: 10000,
      frequency: "monthly",
      startMonth: 0,
      endMonth: null,
      annualGrowthPct: 0.03,
    },
    {
      id: "evt-005",
      name: "Ostatní (doprava, fun, drobnosti)",
      category: "expense",
      amount: 20000,
      frequency: "monthly",
      startMonth: 0,
      endMonth: null,
      annualGrowthPct: 0.025,
    },
    {
      id: "evt-006",
      name: "Dovolená",
      category: "expense",
      amount: 60000,
      frequency: "yearly",
      startMonth: 0,
      endMonth: null,
      annualGrowthPct: 0.04,
    },
  ],
  mortgages: [
    {
      id: "mtg-001",
      name: "Hypo byt",
      principal: 8200000,
      startMonth: 0,
      termMonths: 360,
      rateSchedule: [
        { id: "rs-001", fromMonth: 0, rateAnnual: 0.045 },
        { id: "rs-002", fromMonth: 60, rateAnnual: 0.035 },
      ],
      insuranceMonthly: 500,
    },
  ],
  assets: [],
};
